[package]
name = "k210-shared"
version = "0.1.0"
authors = ["W.J. van der Laan <laanwj@protonmail.com>"]
edition = "2018"

[dependencies]
k210-hal = "0.2.0"
libm = "0.1"
riscv = "0.5"
riscv-rt = "0.7"
